In [2]:
from sensor.utils.main_utils import read_yaml_file

In [3]:
file_path="E:\ineuron\IndustryProjects\Sensor-Fault-Detection\config\schema.yaml"

In [4]:
schema_config = read_yaml_file(file_path=file_path)

In [5]:
len(schema_config['columns'])==len(df.columns)

NameError: name 'df' is not defined

In [6]:
from scipy.stats import ks_2samp

In [7]:
import numpy as np

In [8]:
d1 = np.arange(100,200)
d2 = np.arange(10)

In [9]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [10]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [12]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
test = ks_2samp(d1,d2)

In [14]:
round(test.pvalue)

0

In [20]:
traing_file_path = "artifact/04_14_2023_23_49_19/data_ingestion/ingested/train.csv"

In [19]:
test_file_path = "artifact/04_14_2023_23_49_19/data_ingestion/ingested/test.csv"

In [17]:
import pandas as pd

In [21]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [22]:
train_df.columns

Index(['class', 'aa_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', 'ag_000',
       'ag_001', 'ag_002', 'ag_003',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=164)

In [23]:
test_df.columns

Index(['class', 'aa_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', 'ag_000',
       'ag_001', 'ag_002', 'ag_003',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=164)

In [24]:
from sensor.utils.main_utils import write_yaml_file

In [27]:

def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report



In [28]:
drift_report = get_drift_report(train_df,test_df)

In [29]:
drift_report

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.011252538210652642, 'drift_status': True},
 'ac_000': {'p_value': 0.2592157727379347, 'drift_status': False},
 'ad_000': {'p_value': 0.014000372284973858, 'drift_status': True},
 'ae_000': {'p_value': 0.9999999961201351, 'drift_status': False},
 'af_000': {'p_value': 0.999999892430308, 'drift_status': False},
 'ag_000': {'p_value': 1.0, 'drift_status': False},
 'ag_001': {'p_value': 1.0, 'drift_status': False},
 'ag_002': {'p_value': 0.999692845184693, 'drift_status': False},
 'ag_003': {'p_value': 0.5840101095639024, 'drift_status': False},
 'ag_004': {'p_value': 0.17114912205144373, 'drift_status': False},
 'ag_005': {'p_value': 0.0027141620831688854, 'drift_status': True},
 'ag_006': {'p_value': 0.03858484190529132, 'drift_status': True},
 'ag_007': {'p_value': 0.10756164092833043, 'drift_status': False},
 'ag_008': {'p_value': 0.7209894866753797, 'drift_status': False},
 'ag_009': {'p_value': 0.802187771613

In [31]:
import os
write_yaml_file(file_path=os.path.join(os.getcwd(),"report.yaml"),content=drift_report,replace=True)

In [32]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=5.838240195532585e-05, pvalue=1.0, statistic_location='neg', statistic_sign=-1)

KstestResult(statistic=0.009896540089462558, pvalue=0.6183763526162667)

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [4]:
.to_dict()TargetValueMapping()

{'neg': 0, 'pos': 1}

In [5]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}